name: Build Release Wheels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    name: linux-aarch64 py${{ matrix.python-version }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os-name: linux-aarch64
            runner: ubuntu-latest
            target: aarch64
            python-version: "3.12"
            manylinux: auto
            artifact-name: wheels-linux-aarch64-cp312
          - os-name: linux-aarch64
            runner: ubuntu-latest
            target: aarch64
            python-version: "3.13"
            manylinux: auto
            artifact-name: wheels-linux-aarch64-cp313
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i python
          sccache: "true"
          manylinux: ${{ matrix.manylinux }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/*.whl

  macos:
    name: macos-arm64 py${{ matrix.python-version }}
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.12"
            target: aarch64
            artifact-name: wheels-macos-arm64-cp312
          - python-version: "3.13"
            target: aarch64
            artifact-name: wheels-macos-arm64-cp313
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist -i python
          sccache: "true"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/*.whl
